### ISSUE TITLE
Add RSS feed for the blog

### ISSUE THREAD

**Issue by aciccarello** [cooklang/cooklang.org#17]
There is a mailchip subscription form, but not a way to subscribe via RSS, at least not one that is easily [discoverable via an HTML link tag](https://www.jvt.me/posts/2021/11/10/rss-discovery/).

This would make it easier to subscribe to update.

**Comment by dubadub** [comment]
Deployed, you can find a link in the footer

**Comment by aciccarello** [comment]
Great! Thanks!
